name: Scrape Tables - 24f2003048@ds.study.iitm.ac.in

on:
  push:
    branches: [main]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run Scraper - 24f2003048@ds.study.iitm.ac.in
        run: python scrape.py
